import type { BlogPost } from "../types";

// The three original full posts (moved out of en.ts / de.ts unchanged).

export const existingEn: BlogPost[] = [
  {
    slug: "functioning-well-vs-feeling-well",
    title: "When \"Functioning Well\" Isn't the Same as Feeling Well",
    category: "Stress & Burnout",
    date: "2026-05-28",
    readingTime: "6",
    excerpt:
      "Why high-functioning stress often goes unnoticed, and what the early signs of burnout can look like from the inside.",
    body: [
      { type: "p", text: "From the outside, everything looks fine. You meet your deadlines, you show up for the people who depend on you, you keep the plates spinning. And yet, somewhere underneath the steady surface, something feels off — a low hum of fatigue that sleep doesn't quite touch, a flatness where enthusiasm used to be, a sense that you are managing your life rather than living it." },
      { type: "p", text: "This is the quiet paradox of high-functioning stress. The very competence that earns praise can also hide how depleted a person has become. When you are good at coping, the people around you — and often you yourself — assume you are doing well. Feeling well, however, is a different question altogether." },
      { type: "h2", text: "Functioning is a behaviour. Feeling is an experience." },
      { type: "p", text: "Functioning describes what you can still do: get to work, answer the emails, hold the conversations. Feeling describes what it costs you to do it. For many capable, conscientious people, these two can drift far apart before anyone notices. You can be highly functional and quietly running on empty at the same time." },
      { type: "p", text: "The gap tends to widen slowly. Coping strategies that once felt sustainable — pushing through, staying busy, putting your own needs last — keep working just well enough that there is never an obvious moment to stop. Until, gradually, the effort required to keep going starts to outweigh what you have to give." },
      { type: "h2", text: "Early signs that are easy to dismiss" },
      { type: "p", text: "Overwhelm rarely announces itself dramatically. More often it shows up in small, dismissible ways — the kind of signals it is tempting to explain away as a busy phase." },
      { type: "ul", items: [
        "Rest that doesn't restore — waking tired, weekends that don't refill the tank.",
        "A shrinking emotional range — less joy, less irritation, a general sense of \"meh\".",
        "Small tasks feeling disproportionately heavy.",
        "Withdrawing from the people and activities that usually sustain you.",
        "A body that keeps the score — tension, disrupted sleep, a stomach that knots before the week begins.",
      ] },
      { type: "p", text: "None of these are failures. They are information. The body and nervous system have ways of signalling when the load has become too much for too long — and learning to read those signals early is far kinder than waiting until they become impossible to ignore." },
      { type: "h2", text: "Why \"I should be able to handle this\" keeps people stuck" },
      { type: "p", text: "One of the most common things I hear is some version of \"other people manage, so I should too.\" But the amount of strain you are carrying is not a measure of your strength, and continuing to cope is not the same as being well. The belief that you should be fine can become the very thing that stops you from getting support while it is still light work to do so." },
      { type: "p", text: "There is also a quieter cost. When you spend a long time overriding your own signals — staying calm when you are not, saying yes when you mean no — you can begin to lose contact with yourself. The disconnection people describe is often exactly this: a kind of low-grade estrangement from their own inner life." },
      { type: "h2", text: "A different starting point" },
      { type: "p", text: "Reconnecting usually begins not with doing more, but with noticing. With giving yourself permission to ask a simple, honest question: how am I, actually? Not how am I performing, or how am I managing — but how am I." },
      { type: "p", text: "This is often where [working together in individual counselling](/work-together) can help — a steady, reflective space to slow down and listen to what has gone unnamed. Sometimes that means making sense of how the strain built up. Sometimes it means gently experimenting with new ways of responding — to your own needs, your relationships, and the pace of your life. The aim is not to make you function even better, but to help you feel more like yourself again." },
      { type: "p", text: "If you recognise yourself in any of this, it does not mean something is wrong with you. It may simply mean that something has shifted, and that the ways of coping that carried you this far are asking to be updated. If you are noticing these patterns, you may also find it helpful to read about [the early signs of burnout](/blog/running-on-empty-early-signs-of-burnout). That is not a breakdown. It is an invitation to come back into relationship with yourself." },
    ],
  },
  {
    slug: "what-is-somatic-experiencing",
    title: "What Is Somatic Experiencing — and How Does It Help With Stress?",
    category: "Somatic Experiencing & Nervous System Regulation",
    date: "2026-05-12",
    readingTime: "6",
    excerpt:
      "An accessible introduction to Somatic Experiencing, the nervous system, and why the body matters when we're under stress.",
    body: [
      { type: "p", text: "Most of us are used to thinking about stress as something that happens in the mind — a matter of thoughts, worries, and to-do lists. And it is. But stress also lives in the body. Your heart rate, your breathing, the tension in your shoulders, the knot in your stomach: these are not side effects of a stressful life. They are part of how stress actually works." },
      { type: "p", text: "Somatic Experiencing (SE) is a body-oriented approach, developed by Dr Peter Levine, that takes this seriously. It works with the nervous system and the felt sense of the body to support people in moving through stress and overwhelming experiences — not by analysing them from a distance, but by gently helping the body complete what it could not at the time." },
      { type: "h2", text: "A quick tour of the nervous system" },
      { type: "p", text: "Your autonomic nervous system is constantly, quietly scanning for safety and threat — long before conscious thought gets involved. When it senses a demand it perceives as too much, it mobilises: the familiar fight-or-flight surge of energy. When something feels overwhelming or inescapable, it can do the opposite — shutting down, numbing, going still." },
      { type: "p", text: "These responses are intelligent and protective. The difficulty is that, under sustained pressure, the nervous system can get stuck in a state of high activation or shutdown even after the demand has passed. You may notice this as feeling permanently wired, on edge, exhausted, or strangely flat — as though the body never quite got the message that it is safe to settle." },
      { type: "h2", text: "What Somatic Experiencing actually involves" },
      { type: "p", text: "SE is gentle and gradual. Rather than asking you to relive difficult events in detail, it pays careful attention to the body's present-moment experience — sensations, small impulses, subtle shifts of tension and ease." },
      { type: "ul", items: [
        "Building awareness of body sensations, a little at a time, within a window you can tolerate.",
        "Noticing where there is tension or activation — and, just as importantly, where there is steadiness and ease.",
        "Allowing the nervous system to discharge held energy slowly, so settling feels safe rather than flooding.",
        "Strengthening your felt sense of grounding, so that regulation becomes more available in daily life.",
      ] },
      { type: "p", text: "An important principle is that more is not better. SE works within a person's capacity, moving back and forth between activation and calm so the system learns, experientially, that it can move out of stress and back into balance. Over time, that flexibility tends to generalise — you recover a little faster, settle a little more easily." },
      { type: "h2", text: "Why the body matters when we're under stress" },
      { type: "p", text: "Insight alone — understanding why you feel as you do — is valuable, but it does not always change how the body responds. You can know, rationally, that you are safe and still feel your chest tighten the moment a certain email arrives. That gap is exactly where body-oriented work can help. By involving the nervous system directly, SE supports change at the level where stress is actually held." },
      { type: "p", text: "In my own work, Somatic Experiencing is one perspective among several. I draw on it alongside systemic and mindfulness-based approaches, depending on what feels useful for the person in front of me — you can read more about how we might [work together](/work-together) if this way of working speaks to you. For some people, attention to the body is the missing piece; for others, it is one strand of a broader exploration. If you would like a fuller picture of how these states operate, my [plain-English guide to the nervous system](/blog/nervous-system-plain-english-guide) sits closely alongside this. You will also find [common questions about how Somatic Experiencing is used in sessions](/faq) answered in the FAQ." },
      { type: "h2", text: "A gentler relationship with your own responses" },
      { type: "p", text: "Perhaps the most quietly powerful thing SE offers is a change in relationship to your own reactions. Instead of fighting your tension or being frightened by your fatigue, you begin to meet these states with curiosity — as meaningful signals from a system that has been doing its best to protect you. From that place, grounding and steadiness have room to grow." },
    ],
  },
  {
    slug: "why-big-life-changes-feel-harder",
    title: "Why Big Life Changes Feel Harder Than They \"Should\"",
    category: "Life Transitions",
    date: "2026-04-22",
    readingTime: "5",
    excerpt:
      "Why transitions are emotionally demanding even when they are positive — and what helps when you feel unsteady through change.",
    body: [
      { type: "p", text: "A new job. A move to a city you chose. A relationship beginning, or a long-held dream finally arriving. By every external measure, things are going well — and yet you feel unexpectedly unsteady, tired, or strangely sad. If a part of you is quietly asking why this is so hard when nothing is wrong, you are not alone." },
      { type: "p", text: "We tend to assume that difficult feelings belong to difficult events. So when a positive change leaves us disoriented, we often add a second layer of distress on top of the first: I shouldn't feel this way. But transitions are demanding by their very nature — not because something has gone wrong, but because change asks a great deal of us, even when it is welcome." },
      { type: "h2", text: "Every gain contains a loss" },
      { type: "p", text: "Beneath almost every meaningful change is something being left behind. A new role means letting go of the comfort of competence you had in the old one. A move forward in life can quietly close the door on a version of yourself, or a way of living, that you were attached to. These losses are often invisible — even to us — which is part of why the feelings that come with them can be so confusing." },
      { type: "p", text: "Naming the loss inside the gain is often a relief. It explains the grief that can sit, unexpectedly, beside genuine excitement. You are not being ungrateful. You are metabolising a real change." },
      { type: "h2", text: "Transitions ask the nervous system to recalibrate" },
      { type: "p", text: "Familiarity is a form of safety. Even routines we complain about provide a kind of scaffolding the nervous system relies on. When that scaffolding changes — new surroundings, new people, new expectations — the body has to work harder, orienting to everything afresh. That extra effort is real, and it is tiring, which is why transitions so often come with a fatigue that pure logic can't account for." },
      { type: "ul", items: [
        "The \"in-between\" feeling — no longer who you were, not yet who you are becoming.",
        "Heightened sensitivity, self-doubt, or a shorter fuse than usual.",
        "Tiredness that rest doesn't fully resolve.",
        "Waves of emotion that seem out of proportion to events.",
      ] },
      { type: "h2", text: "The space between is not a mistake" },
      { type: "p", text: "Many traditions describe transition as a threshold — a liminal space between an old structure and a new one. It is uncomfortable precisely because it is unformed. But it is also where genuine reorientation happens. Rushing to feel settled can short-circuit the very process that allows something new to take shape." },
      { type: "p", text: "What helps, more often than not, is permission: to feel unsteady without treating it as a problem to be solved; to move at a humane pace; to stay in contact with your values while the outer details rearrange themselves." },
      { type: "h2", text: "Support through the in-between" },
      { type: "p", text: "This is often where [working together in counselling](/work-together) helps — a steady point of reference while everything else is shifting, a reflective space to make sense of what is being left behind, what is being asked of you, and what matters most as you move forward. Not to speed the transition up, but to help you move through it with more steadiness and self-understanding. If your particular change involves a move to a new country, you may also recognise yourself in this piece on [the stress of adjusting to a new country](/blog/relocation-stress-adjusting-new-country)." },
      { type: "p", text: "If a change that should feel good is leaving you more tender than you expected, consider it a sign of how much the moment is asking of you — and how much it matters. That is not weakness. It is the ordinary, demanding work of becoming." },
    ],
  },
];

export const existingDe: BlogPost[] = [
  {
    slug: "functioning-well-vs-feeling-well",
    title: "Wenn „gut funktionieren\" nicht heißt, dass es einem gut geht",
    category: "Stress & Überforderung",
    date: "2026-05-28",
    readingTime: "6",
    excerpt:
      "Warum Stress bei Menschen, die weiter gut funktionieren, oft übersehen wird und wie sich die ersten Anzeichen von Überforderung von innen anfühlen.",
    body: [
      { type: "p", text: "Von außen wirkt alles in Ordnung. Sie halten Ihre Termine ein, Sie sind für die Menschen da, die auf Sie zählen, Sie halten alle Bälle in der Luft. Und doch stimmt irgendwo unter der ruhigen Oberfläche etwas nicht — eine leise, dauernde Müdigkeit, gegen die auch Schlaf nicht ankommt, eine Leere dort, wo früher Begeisterung war, das Gefühl, das eigene Leben eher zu verwalten als zu leben." },
      { type: "p", text: "Das ist das stille Paradox: Wer nach außen bestens funktioniert, steht innerlich oft unter enormem Druck. Gerade die Tüchtigkeit, für die man Anerkennung bekommt, verbirgt, wie erschöpft man längst ist. Wer gut damit umgehen kann, dem trauen die anderen — und oft auch man selbst — zu, dass alles in Ordnung ist. Ob es einem wirklich gut geht, ist damit aber noch lange nicht gesagt." },
      { type: "h2", text: "Funktionieren ist ein Verhalten. Fühlen ist ein Erleben." },
      { type: "p", text: "Funktionieren beschreibt, was Sie noch schaffen: zur Arbeit gehen, die E-Mails beantworten, die Gespräche führen. Fühlen beschreibt, was es Sie kostet. Bei vielen fähigen, gewissenhaften Menschen können diese beiden weit auseinandergehen, bevor es überhaupt jemandem auffällt. Man kann bestens funktionieren und dabei still auf dem Zahnfleisch gehen." },
      { type: "p", text: "Der Abstand wächst meist ganz allmählich. Bewältigungsstrategien, die sich einmal tragfähig anfühlten — durchhalten, sich beschäftigt halten, die eigenen Bedürfnisse hintanstellen — tragen gerade so weit, dass es nie einen klaren Moment zum Innehalten gibt. Bis irgendwann die Mühe, weiterzumachen, mehr wird, als man noch aufbringen kann." },
      { type: "h2", text: "Frühe Anzeichen, die man leicht übergeht" },
      { type: "p", text: "Überforderung kündigt sich selten mit Getöse an. Häufiger zeigt sie sich in kleinen, leicht zu übergehenden Dingen — Signale, die man nur zu gern als vorübergehend stressige Phase abtut." },
      { type: "ul", items: [
        "Ruhe, die nicht erholt — man wacht müde auf, Wochenenden füllen die Reserven nicht wieder auf.",
        "Eine schrumpfende Gefühlswelt — weniger Freude, weniger Ärger, ein allgemeines „ist mir alles einerlei\".",
        "Kleine Aufgaben, die sich unverhältnismäßig schwer anfühlen.",
        "Der Rückzug von den Menschen und Dingen, die einem sonst Halt geben.",
        "Ein Körper, der Buch führt — Anspannung, unruhiger Schlaf, ein Magen, der sich schon vor Wochenbeginn verkrampft.",
      ] },
      { type: "p", text: "Nichts davon ist ein Versagen. Es sind Hinweise. Körper und Nervensystem haben ihre Wege zu zeigen, wenn die Last zu lange zu groß ist — und diese Zeichen früh zu erkennen, ist weit gütiger, als zu warten, bis sie sich nicht mehr übersehen lassen." },
      { type: "h2", text: "Warum „ich sollte das doch hinkriegen\" so viele festhält" },
      { type: "p", text: "Einer der Sätze, die ich am häufigsten höre, geht ungefähr so: „Andere schaffen das doch auch, also sollte ich das auch.\" Doch wie viel Sie gerade zu tragen haben, sagt nichts über Ihre Stärke aus, und weiter durchzuhalten heißt noch nicht, dass es Ihnen gut geht. Die Überzeugung, dass eigentlich alles in Ordnung sein müsste, kann Sie gerade davon abhalten, sich Unterstützung zu holen, solange das noch mit wenig Aufwand möglich wäre." },
      { type: "p", text: "Es gibt noch einen leiseren Preis. Wenn Sie über lange Zeit die eigenen Signale übergehen — ruhig bleiben, obwohl Sie es nicht sind, Ja sagen, wenn Sie Nein meinen —, verlieren Sie womöglich den Kontakt zu sich selbst. Diese Entfremdung, die viele beschreiben, ist oft genau das: ein leises Sich-fremd-Werden gegenüber dem eigenen Innenleben." },
      { type: "h2", text: "Ein anderer Anfang" },
      { type: "p", text: "Wieder in Verbindung zu kommen, beginnt meist nicht damit, mehr zu tun, sondern damit, wahrzunehmen. Sich selbst zu erlauben, eine einfache, ehrliche Frage zu stellen: Wie geht es mir eigentlich? Nicht wie funktioniere ich, nicht wie halte ich durch — sondern wie es mir geht." },
      { type: "p", text: "Genau hier kann [die Einzelberatung](/de/work-together) helfen — ein verlässlicher Raum zum Nachdenken, um zur Ruhe zu kommen und dem zuzuhören, was bisher unausgesprochen blieb. Manchmal geht es darum, zu verstehen, wie sich die Belastung aufgebaut hat. Manchmal darum, behutsam neue Wege auszuprobieren, mit den eigenen Bedürfnissen, den Beziehungen und dem Tempo des eigenen Lebens umzugehen. Das Ziel ist nicht, dass Sie noch besser funktionieren, sondern dass Sie sich wieder mehr wie Sie selbst fühlen." },
      { type: "p", text: "Wenn Sie sich in irgendetwas davon wiedererkennen, heißt das nicht, dass mit Ihnen etwas nicht stimmt. Es kann schlicht heißen, dass sich etwas verschoben hat und dass die Bewältigungsweisen, die Sie bis hierher getragen haben, ein Update brauchen. Wenn Ihnen diese Muster bekannt vorkommen, hilft Ihnen vielleicht auch der Beitrag über [die frühen Anzeichen von Burnout](/de/blog/running-on-empty-early-signs-of-burnout). Das ist kein Zusammenbruch. Es ist eine Einladung, wieder in Beziehung zu sich selbst zu treten." },
    ],
  },
  {
    slug: "what-is-somatic-experiencing",
    title: "Was ist Somatic Experiencing — und wie hilft es bei Stress?",
    category: "Somatic Experiencing & Regulation des Nervensystems",
    date: "2026-05-12",
    readingTime: "6",
    excerpt:
      "Eine leicht verständliche Einführung in Somatic Experiencing, das Nervensystem und warum der Körper wichtig ist, wenn wir unter Stress stehen.",
    body: [
      { type: "p", text: "Die meisten von uns denken bei Stress zuerst an etwas, das im Kopf passiert — an Gedanken, Sorgen und To-do-Listen. Das stimmt auch. Aber Stress sitzt genauso im Körper. Ihr Herzschlag, Ihre Atmung, die verspannten Schultern, der Knoten im Magen: Das sind keine Nebenwirkungen eines stressigen Lebens. So wirkt Stress tatsächlich." },
      { type: "p", text: "Somatic Experiencing (SE) ist ein körperorientierter Ansatz, den Dr. Peter Levine entwickelt hat und der genau das ernst nimmt. Er arbeitet mit dem Nervensystem und dem, was der Körper spürt, um Menschen dabei zu begleiten, durch Stress und überwältigende Erfahrungen hindurchzufinden — nicht, indem man sie aus der Distanz analysiert, sondern indem der Körper behutsam nachholen darf, was ihm damals nicht möglich war." },
      { type: "h2", text: "Ein kurzer Blick auf das Nervensystem" },
      { type: "p", text: "Ihr autonomes Nervensystem prüft ständig und ganz leise, ob gerade Sicherheit oder Gefahr herrscht — lange bevor bewusstes Denken einsetzt. Nimmt es eine Anforderung als zu groß wahr, macht es mobil: der vertraute Energieschub von Kampf oder Flucht. Fühlt sich etwas überwältigend oder ausweglos an, kann es das Gegenteil tun — herunterfahren, abstumpfen, erstarren." },
      { type: "p", text: "Diese Reaktionen sind klug und schützen uns. Das Schwierige ist nur: Unter anhaltendem Druck kann das Nervensystem in hoher Anspannung oder im Herunterfahren stecken bleiben, auch wenn die Anforderung längst vorüber ist. Das kann sich so anfühlen, als stünden Sie dauernd unter Strom, angespannt, erschöpft oder seltsam leer — als hätte der Körper nie ganz mitbekommen, dass er sich wieder beruhigen darf." },
      { type: "h2", text: "Was bei Somatic Experiencing wirklich geschieht" },
      { type: "p", text: "SE geht behutsam und in kleinen Schritten vor. Statt Sie zu bitten, schwierige Erlebnisse noch einmal in allen Einzelheiten zu durchleben, richtet sich die Aufmerksamkeit sorgfältig darauf, was der Körper im Augenblick spürt — Empfindungen, kleine Impulse, feine Wechsel zwischen Anspannung und Leichtigkeit." },
      { type: "ul", items: [
        "Nach und nach ein Gespür für Körperempfindungen entwickeln, immer nur so viel, wie sich gut aushalten lässt.",
        "Wahrnehmen, wo Anspannung oder Aktivierung sitzt — und ebenso wichtig, wo Halt und Leichtigkeit sind.",
        "Dem Nervensystem erlauben, gebundene Energie langsam abzugeben, sodass sich das Zur-Ruhe-Kommen sicher anfühlt und nicht überschwemmend.",
        "Das Gefühl innerer Erdung stärken, damit Ihnen Regulation im Alltag leichter zur Verfügung steht.",
      ] },
      { type: "p", text: "Ein wichtiger Grundsatz lautet: Mehr ist nicht besser. SE bleibt im Rahmen dessen, was ein Mensch tragen kann, und pendelt zwischen Anspannung und Ruhe hin und her, sodass das System aus eigener Erfahrung lernt, dass es aus dem Stress heraus und wieder ins Gleichgewicht zurückfinden kann. Mit der Zeit überträgt sich diese Beweglichkeit auf den Alltag — Sie erholen sich etwas schneller, kommen etwas leichter zur Ruhe." },
      { type: "h2", text: "Warum der Körper wichtig ist, wenn wir unter Stress stehen" },
      { type: "p", text: "Einsicht allein — zu verstehen, warum es Ihnen so geht, wie es Ihnen geht — ist wertvoll, ändert aber nicht immer, wie der Körper reagiert. Sie können ganz rational wissen, dass Sie sicher sind, und trotzdem spüren, wie sich Ihre Brust zusammenzieht, sobald eine bestimmte E-Mail eintrifft. Genau da kann körperorientierte Arbeit ansetzen. Indem SE das Nervensystem unmittelbar einbezieht, unterstützt es Veränderung dort, wo Stress tatsächlich sitzt." },
      { type: "p", text: "In meiner Arbeit ist Somatic Experiencing eine Sichtweise unter mehreren. Ich greife darauf neben systemischen und achtsamkeitsbasierten Ansätzen zurück, je nachdem, was dem Menschen vor mir gerade guttut — wie eine [Zusammenarbeit](/de/work-together) aussehen könnte, erfahren Sie, wenn Sie diese Arbeitsweise anspricht. Für manche ist die Aufmerksamkeit für den Körper das fehlende Stück; für andere ist sie ein Faden in einer umfassenderen Auseinandersetzung. Wenn Sie ein umfassenderes Bild davon möchten, wie diese Zustände wirken, passt meine [verständliche Einführung in das Nervensystem](/de/blog/nervous-system-plain-english-guide) eng dazu. Häufige Fragen dazu, wie Somatic Experiencing in den Sitzungen zum Einsatz kommt, beantworte ich in den [FAQ](/de/faq)." },
      { type: "h2", text: "Ein freundlicherer Umgang mit den eigenen Reaktionen" },
      { type: "p", text: "Das vielleicht am stillsten Wirksame an SE ist, dass sich Ihr Verhältnis zu den eigenen Reaktionen verändert. Statt gegen Ihre Anspannung anzukämpfen oder vor Ihrer Erschöpfung zu erschrecken, beginnen Sie, diesen Zuständen mit Neugier zu begegnen — als bedeutsame Signale eines Systems, das nach Kräften versucht hat, Sie zu schützen. Von hier aus haben Erdung und innerer Halt Raum zu wachsen." },
    ],
  },
  {
    slug: "why-big-life-changes-feel-harder",
    title: "Warum sich große Lebensveränderungen schwerer anfühlen, als sie „dürften\"",
    category: "Lebensübergänge",
    date: "2026-04-22",
    readingTime: "5",
    excerpt:
      "Warum Übergänge emotional fordern, selbst wenn sie positiv sind — und was hilft, wenn Ihnen mitten in der Veränderung der Boden schwankt.",
    body: [
      { type: "p", text: "Ein neuer Job. Ein Umzug in eine Stadt, für die Sie sich selbst entschieden haben. Eine Beziehung, die beginnt, oder ein lang gehegter Traum, der endlich wahr wird. Nach allen äußeren Maßstäben läuft es gut — und trotzdem fühlen Sie sich unerwartet haltlos, müde oder seltsam traurig. Wenn ein Teil von Ihnen leise fragt, warum das so schwer ist, obwohl doch nichts falsch läuft, dann geht es Ihnen wie vielen." },
      { type: "p", text: "Wir gehen meist davon aus, dass schwere Gefühle zu schweren Ereignissen gehören. Wirft uns also eine positive Veränderung aus der Bahn, legen wir gern noch eine zweite Last auf die erste: So sollte ich mich doch nicht fühlen. Doch Übergänge fordern von Natur aus — nicht, weil etwas schiefgelaufen wäre, sondern weil Veränderung uns viel abverlangt, selbst wenn sie willkommen ist." },
      { type: "h2", text: "In jedem Gewinn steckt ein Verlust" },
      { type: "p", text: "Unter fast jeder bedeutsamen Veränderung liegt etwas, das zurückbleibt. Eine neue Rolle heißt, die vertraute Sicherheit loszulassen, die man in der alten hatte. Ein Schritt nach vorn kann leise die Tür zu einer früheren Version Ihrer selbst oder zu einer Lebensweise schließen, an der Sie hingen. Solche Verluste bleiben oft unsichtbar — auch für uns selbst —, und das ist mit ein Grund, warum die Gefühle, die sie begleiten, so verwirrend sein können." },
      { type: "p", text: "Den Verlust im Gewinn zu benennen, ist oft eine Erleichterung. Es erklärt die Trauer, die unversehens neben echter Vorfreude sitzen kann. Sie sind nicht undankbar. Sie verarbeiten eine echte Veränderung." },
      { type: "h2", text: "Übergänge verlangen dem Nervensystem eine Neuausrichtung ab" },
      { type: "p", text: "Vertrautheit ist eine Form von Sicherheit. Selbst Routinen, über die wir schimpfen, geben ein Gerüst ab, auf das sich das Nervensystem verlässt. Wenn dieses Gerüst sich ändert — neue Umgebung, neue Menschen, neue Erwartungen —, muss der Körper mehr leisten und sich in allem neu zurechtfinden. Diese zusätzliche Anstrengung ist real, und sie ermüdet. Deshalb geht mit Übergängen so oft eine Erschöpfung einher, für die es keine rein logische Erklärung gibt." },
      { type: "ul", items: [
        "Das Gefühl, dazwischen zu hängen — nicht mehr, wer Sie waren, noch nicht, wer Sie werden.",
        "Größere Empfindsamkeit, Selbstzweifel oder ein kürzerer Geduldsfaden als sonst.",
        "Müdigkeit, die auch mit Ruhe nicht ganz verschwindet.",
        "Gefühlswellen, die in keinem Verhältnis zu dem stehen, was gerade passiert.",
      ] },
      { type: "h2", text: "Das Dazwischen ist kein Fehler" },
      { type: "p", text: "Viele Traditionen beschreiben den Übergang als Schwelle — als Zwischenraum zwischen einer alten Ordnung und einer neuen. Gerade weil er noch ungeformt ist, fühlt er sich unbequem an. Aber genau hier geschieht echte Neuorientierung. Wer sich drängt, möglichst rasch wieder festen Boden zu spüren, bringt womöglich genau den Prozess durcheinander, der es etwas Neuem erlaubt, Gestalt anzunehmen." },
      { type: "p", text: "Was meist hilft, ist Erlaubnis: sich haltlos fühlen zu dürfen, ohne es als Problem zu behandeln, das gelöst werden muss; sich in einem menschlichen Tempo zu bewegen; in Kontakt mit den eigenen Werten zu bleiben, während sich die äußeren Dinge neu ordnen." },
      { type: "h2", text: "Begleitung durch das Dazwischen" },
      { type: "p", text: "Genau hier hilft oft [die Beratung](/de/work-together) — ein verlässlicher Bezugspunkt, während sich alles andere verschiebt, ein Raum zum Nachdenken, um zu verstehen, was zurückbleibt, was von Ihnen verlangt wird und was am meisten zählt, während Sie weitergehen. Nicht, um den Übergang zu beschleunigen, sondern um Ihnen zu helfen, ihn mit mehr Halt und mehr Verständnis für sich selbst zu durchleben. Wenn zu Ihrer Veränderung ein Umzug in ein neues Land gehört, erkennen Sie sich vielleicht auch in diesem Beitrag über [den Stress, in einem neuen Land anzukommen](/de/blog/relocation-stress-adjusting-new-country), wieder." },
      { type: "p", text: "Wenn eine Veränderung, die sich eigentlich gut anfühlen sollte, Sie verletzlicher macht, als Sie erwartet haben, dann nehmen Sie das als Zeichen dafür, wie viel dieser Moment Ihnen abverlangt — und wie sehr er zählt. Das ist keine Schwäche. Es ist die ganz gewöhnliche, fordernde Arbeit des Werdens." },
    ],
  },
];
