import type { BlogPost } from "../types";

// The three original full posts (moved out of en.ts / de.ts unchanged).

export const existingEn: BlogPost[] = [
  {
    slug: "functioning-well-vs-feeling-well",
    title: "When \"Functioning Well\" Isn't the Same as Feeling Well",
    category: "Stress & Burnout",
    date: "2026-05-28",
    readingTime: "6",
    excerpt:
      "Why high-functioning stress often goes unnoticed, and what the early signs of burnout can look like from the inside.",
    body: [
      { type: "p", text: "From the outside, everything looks fine. You meet your deadlines, you show up for the people who depend on you, you keep the plates spinning. And yet, somewhere underneath the steady surface, something feels off — a low hum of fatigue that sleep doesn't quite touch, a flatness where enthusiasm used to be, a sense that you are managing your life rather than living it." },
      { type: "p", text: "This is the quiet paradox of high-functioning stress. The very competence that earns praise can also hide how depleted a person has become. When you are good at coping, the people around you — and often you yourself — assume you are doing well. Feeling well, however, is a different question altogether." },
      { type: "h2", text: "Functioning is a behaviour. Feeling is an experience." },
      { type: "p", text: "Functioning describes what you can still do: get to work, answer the emails, hold the conversations. Feeling describes what it costs you to do it. For many capable, conscientious people, these two can drift far apart before anyone notices. You can be highly functional and quietly running on empty at the same time." },
      { type: "p", text: "The gap tends to widen slowly. Coping strategies that once felt sustainable — pushing through, staying busy, putting your own needs last — keep working just well enough that there is never an obvious moment to stop. Until, gradually, the effort required to keep going starts to outweigh what you have to give." },
      { type: "h2", text: "Early signs that are easy to dismiss" },
      { type: "p", text: "Overwhelm rarely announces itself dramatically. More often it shows up in small, dismissible ways — the kind of signals it is tempting to explain away as a busy phase." },
      { type: "ul", items: [
        "Rest that doesn't restore — waking tired, weekends that don't refill the tank.",
        "A shrinking emotional range — less joy, less irritation, a general sense of \"meh\".",
        "Small tasks feeling disproportionately heavy.",
        "Withdrawing from the people and activities that usually sustain you.",
        "A body that keeps the score — tension, disrupted sleep, a stomach that knots before the week begins.",
      ] },
      { type: "p", text: "None of these are failures. They are information. The body and nervous system have ways of signalling when the load has become too much for too long — and learning to read those signals early is far kinder than waiting until they become impossible to ignore." },
      { type: "h2", text: "Why \"I should be able to handle this\" keeps people stuck" },
      { type: "p", text: "One of the most common things I hear is some version of \"other people manage, so I should too.\" But the amount of strain you are carrying is not a measure of your strength, and continuing to cope is not the same as being well. The belief that you should be fine can become the very thing that stops you from getting support while it is still light work to do so." },
      { type: "p", text: "There is also a quieter cost. When you spend a long time overriding your own signals — staying calm when you are not, saying yes when you mean no — you can begin to lose contact with yourself. The disconnection people describe is often exactly this: a kind of low-grade estrangement from their own inner life." },
      { type: "h2", text: "A different starting point" },
      { type: "p", text: "Reconnecting usually begins not with doing more, but with noticing. With giving yourself permission to ask a simple, honest question: how am I, actually? Not how am I performing, or how am I managing — but how am I." },
      { type: "p", text: "Counselling can offer a steady, reflective space to slow down and listen to what has gone unnamed. Sometimes that means making sense of how the strain built up. Sometimes it means gently experimenting with new ways of responding — to your own needs, your relationships, and the pace of your life. The aim is not to make you function even better, but to help you feel more like yourself again." },
      { type: "p", text: "If you recognise yourself in any of this, it does not mean something is wrong with you. It may simply mean that something has shifted, and that the ways of coping that carried you this far are asking to be updated. That is not a breakdown. It is an invitation to come back into relationship with yourself." },
    ],
  },
  {
    slug: "what-is-somatic-experiencing",
    title: "What Is Somatic Experiencing — and How Does It Help With Stress?",
    category: "Somatic Experiencing & Nervous System Regulation",
    date: "2026-05-12",
    readingTime: "6",
    excerpt:
      "An accessible introduction to Somatic Experiencing, the nervous system, and why the body matters when we're under stress.",
    body: [
      { type: "p", text: "Most of us are used to thinking about stress as something that happens in the mind — a matter of thoughts, worries, and to-do lists. And it is. But stress also lives in the body. Your heart rate, your breathing, the tension in your shoulders, the knot in your stomach: these are not side effects of a stressful life. They are part of how stress actually works." },
      { type: "p", text: "Somatic Experiencing (SE) is a body-oriented approach, developed by Dr Peter Levine, that takes this seriously. It works with the nervous system and the felt sense of the body to support people in moving through stress and overwhelming experiences — not by analysing them from a distance, but by gently helping the body complete what it could not at the time." },
      { type: "h2", text: "A quick tour of the nervous system" },
      { type: "p", text: "Your autonomic nervous system is constantly, quietly scanning for safety and threat — long before conscious thought gets involved. When it senses a demand it perceives as too much, it mobilises: the familiar fight-or-flight surge of energy. When something feels overwhelming or inescapable, it can do the opposite — shutting down, numbing, going still." },
      { type: "p", text: "These responses are intelligent and protective. The difficulty is that, under sustained pressure, the nervous system can get stuck in a state of high activation or shutdown even after the demand has passed. You may notice this as feeling permanently wired, on edge, exhausted, or strangely flat — as though the body never quite got the message that it is safe to settle." },
      { type: "h2", text: "What Somatic Experiencing actually involves" },
      { type: "p", text: "SE is gentle and gradual. Rather than asking you to relive difficult events in detail, it pays careful attention to the body's present-moment experience — sensations, small impulses, subtle shifts of tension and ease." },
      { type: "ul", items: [
        "Building awareness of body sensations, a little at a time, within a window you can tolerate.",
        "Noticing where there is tension or activation — and, just as importantly, where there is steadiness and ease.",
        "Allowing the nervous system to discharge held energy slowly, so settling feels safe rather than flooding.",
        "Strengthening your felt sense of grounding, so that regulation becomes more available in daily life.",
      ] },
      { type: "p", text: "An important principle is that more is not better. SE works within a person's capacity, moving back and forth between activation and calm so the system learns, experientially, that it can move out of stress and back into balance. Over time, that flexibility tends to generalise — you recover a little faster, settle a little more easily." },
      { type: "h2", text: "Why the body matters when we're under stress" },
      { type: "p", text: "Insight alone — understanding why you feel as you do — is valuable, but it does not always change how the body responds. You can know, rationally, that you are safe and still feel your chest tighten the moment a certain email arrives. That gap is exactly where body-oriented work can help. By involving the nervous system directly, SE supports change at the level where stress is actually held." },
      { type: "p", text: "In my own work, Somatic Experiencing is one perspective among several. I draw on it alongside systemic and mindfulness-based approaches, depending on what feels useful for the person in front of me. For some people, attention to the body is the missing piece; for others, it is one strand of a broader exploration." },
      { type: "h2", text: "A gentler relationship with your own responses" },
      { type: "p", text: "Perhaps the most quietly powerful thing SE offers is a change in relationship to your own reactions. Instead of fighting your tension or being frightened by your fatigue, you begin to meet these states with curiosity — as meaningful signals from a system that has been doing its best to protect you. From that place, grounding and steadiness have room to grow." },
    ],
  },
  {
    slug: "why-big-life-changes-feel-harder",
    title: "Why Big Life Changes Feel Harder Than They \"Should\"",
    category: "Life Transitions",
    date: "2026-04-22",
    readingTime: "5",
    excerpt:
      "Why transitions are emotionally demanding even when they are positive — and what helps when you feel unsteady through change.",
    body: [
      { type: "p", text: "A new job. A move to a city you chose. A relationship beginning, or a long-held dream finally arriving. By every external measure, things are going well — and yet you feel unexpectedly unsteady, tired, or strangely sad. If a part of you is quietly asking why this is so hard when nothing is wrong, you are not alone." },
      { type: "p", text: "We tend to assume that difficult feelings belong to difficult events. So when a positive change leaves us disoriented, we often add a second layer of distress on top of the first: I shouldn't feel this way. But transitions are demanding by their very nature — not because something has gone wrong, but because change asks a great deal of us, even when it is welcome." },
      { type: "h2", text: "Every gain contains a loss" },
      { type: "p", text: "Beneath almost every meaningful change is something being left behind. A new role means letting go of the comfort of competence you had in the old one. A move forward in life can quietly close the door on a version of yourself, or a way of living, that you were attached to. These losses are often invisible — even to us — which is part of why the feelings that come with them can be so confusing." },
      { type: "p", text: "Naming the loss inside the gain is often a relief. It explains the grief that can sit, unexpectedly, beside genuine excitement. You are not being ungrateful. You are metabolising a real change." },
      { type: "h2", text: "Transitions ask the nervous system to recalibrate" },
      { type: "p", text: "Familiarity is a form of safety. Even routines we complain about provide a kind of scaffolding the nervous system relies on. When that scaffolding changes — new surroundings, new people, new expectations — the body has to work harder, orienting to everything afresh. That extra effort is real, and it is tiring, which is why transitions so often come with a fatigue that pure logic can't account for." },
      { type: "ul", items: [
        "The \"in-between\" feeling — no longer who you were, not yet who you are becoming.",
        "Heightened sensitivity, self-doubt, or a shorter fuse than usual.",
        "Tiredness that rest doesn't fully resolve.",
        "Waves of emotion that seem out of proportion to events.",
      ] },
      { type: "h2", text: "The space between is not a mistake" },
      { type: "p", text: "Many traditions describe transition as a threshold — a liminal space between an old structure and a new one. It is uncomfortable precisely because it is unformed. But it is also where genuine reorientation happens. Rushing to feel settled can short-circuit the very process that allows something new to take shape." },
      { type: "p", text: "What helps, more often than not, is permission: to feel unsteady without treating it as a problem to be solved; to move at a humane pace; to stay in contact with your values while the outer details rearrange themselves." },
      { type: "h2", text: "Support through the in-between" },
      { type: "p", text: "Counselling can offer a steady point of reference while everything else is shifting — a reflective space to make sense of what is being left behind, what is being asked of you, and what matters most as you move forward. Not to speed the transition up, but to help you move through it with more steadiness and self-understanding." },
      { type: "p", text: "If a change that should feel good is leaving you more tender than you expected, consider it a sign of how much the moment is asking of you — and how much it matters. That is not weakness. It is the ordinary, demanding work of becoming." },
    ],
  },
];

export const existingDe: BlogPost[] = [
  {
    slug: "functioning-well-vs-feeling-well",
    title: "Wenn „gut funktionieren\" nicht dasselbe ist wie sich gut fühlen",
    category: "Stress & Überforderung",
    date: "2026-05-28",
    readingTime: "6",
    excerpt:
      "Warum hochfunktionaler Stress oft unbemerkt bleibt und wie die frühen Anzeichen von Überforderung von innen aussehen können.",
    body: [
      { type: "p", text: "Von außen sieht alles in Ordnung aus. Sie halten Ihre Termine ein, Sie sind für die Menschen da, die auf Sie zählen, Sie halten alle Bälle in der Luft. Und doch fühlt sich irgendwo unter der ruhigen Oberfläche etwas falsch an — ein leises Summen von Erschöpfung, das der Schlaf nicht ganz erreicht, eine Flachheit dort, wo früher Begeisterung war, ein Gefühl, dass Sie Ihr Leben eher verwalten als leben." },
      { type: "p", text: "Das ist das stille Paradox hochfunktionalen Stresses. Genau die Tüchtigkeit, die Lob einbringt, kann zugleich verbergen, wie erschöpft ein Mensch geworden ist. Wenn Sie gut darin sind zu bewältigen, gehen die Menschen um Sie herum — und oft auch Sie selbst — davon aus, dass es Ihnen gut geht. Sich gut zu fühlen ist jedoch eine ganz andere Frage." },
      { type: "h2", text: "Funktionieren ist ein Verhalten. Fühlen ist ein Erleben." },
      { type: "p", text: "Funktionieren beschreibt, was Sie noch tun können: zur Arbeit kommen, die E-Mails beantworten, die Gespräche führen. Fühlen beschreibt, was es Sie kostet, das zu tun. Bei vielen fähigen, gewissenhaften Menschen können diese beiden weit auseinanderdriften, bevor es jemand bemerkt. Sie können hochfunktional sein und zugleich still auf Reserve laufen." },
      { type: "p", text: "Die Kluft weitet sich meist langsam. Bewältigungsstrategien, die sich einmal tragfähig anfühlten — durchhalten, beschäftigt bleiben, die eigenen Bedürfnisse hintanstellen — funktionieren gerade so gut, dass es nie einen offensichtlichen Moment zum Innehalten gibt. Bis allmählich die Anstrengung, weiterzumachen, das übersteigt, was Sie zu geben haben." },
      { type: "h2", text: "Frühe Anzeichen, die sich leicht abtun lassen" },
      { type: "p", text: "Überforderung kündigt sich selten dramatisch an. Häufiger zeigt sie sich auf kleine, leicht abzutuende Weise — die Art von Signalen, die man verführerisch leicht als bloß stressige Phase erklären kann." },
      { type: "ul", items: [
        "Ruhe, die nicht erholt — müde aufwachen, Wochenenden, die den Tank nicht wieder füllen.",
        "Eine schrumpfende emotionale Bandbreite — weniger Freude, weniger Gereiztheit, ein allgemeines Gefühl von „naja\".",
        "Kleine Aufgaben fühlen sich unverhältnismäßig schwer an.",
        "Rückzug von den Menschen und Tätigkeiten, die Sie sonst tragen.",
        "Ein Körper, der mitzählt — Anspannung, gestörter Schlaf, ein Magen, der sich verknotet, bevor die Woche beginnt.",
      ] },
      { type: "p", text: "Nichts davon ist ein Versagen. Es sind Informationen. Körper und Nervensystem haben Wege zu signalisieren, wenn die Last zu lange zu groß geworden ist — und zu lernen, diese Signale früh zu lesen, ist weitaus freundlicher, als zu warten, bis sie unmöglich zu übersehen sind." },
      { type: "h2", text: "Warum „ich sollte das doch hinbekommen\" Menschen festhält" },
      { type: "p", text: "Eines der häufigsten Dinge, die ich höre, ist eine Variante von „andere schaffen das, also sollte ich das auch\". Aber das Maß der Belastung, die Sie tragen, ist kein Maßstab für Ihre Stärke, und weiter zu bewältigen ist nicht dasselbe, wie es Ihnen gut geht. Die Überzeugung, dass es Ihnen eigentlich gut gehen müsste, kann genau das werden, was Sie davon abhält, sich Unterstützung zu holen, solange das noch leicht zu tun ist." },
      { type: "p", text: "Es gibt auch einen leiseren Preis. Wenn Sie lange Zeit Ihre eigenen Signale übergehen — ruhig bleiben, obwohl Sie es nicht sind, Ja sagen, wenn Sie Nein meinen — können Sie den Kontakt zu sich selbst verlieren. Die Entfremdung, die Menschen beschreiben, ist oft genau das: eine Art leise Entfremdung vom eigenen Innenleben." },
      { type: "h2", text: "Ein anderer Ausgangspunkt" },
      { type: "p", text: "Wiederverbindung beginnt meist nicht damit, mehr zu tun, sondern damit, wahrzunehmen. Damit, sich selbst die Erlaubnis zu geben, eine einfache, ehrliche Frage zu stellen: Wie geht es mir eigentlich? Nicht wie funktioniere ich oder wie bewältige ich — sondern wie es mir geht." },
      { type: "p", text: "Beratung kann einen verlässlichen, reflexiven Raum bieten, um zur Ruhe zu kommen und dem zuzuhören, was unbenannt geblieben ist. Manchmal heißt das, zu verstehen, wie sich die Belastung aufgebaut hat. Manchmal heißt es, behutsam mit neuen Weisen des Reagierens zu experimentieren — auf Ihre eigenen Bedürfnisse, Ihre Beziehungen und das Tempo Ihres Lebens. Das Ziel ist nicht, dass Sie noch besser funktionieren, sondern Ihnen dabei zu helfen, sich wieder mehr wie Sie selbst zu fühlen." },
      { type: "p", text: "Wenn Sie sich in irgendetwas davon wiedererkennen, bedeutet das nicht, dass mit Ihnen etwas nicht stimmt. Es kann einfach bedeuten, dass sich etwas verschoben hat und dass die Bewältigungsweisen, die Sie bis hierher getragen haben, danach verlangen, aktualisiert zu werden. Das ist kein Zusammenbruch. Es ist eine Einladung, wieder in Beziehung mit sich selbst zu treten." },
    ],
  },
  {
    slug: "what-is-somatic-experiencing",
    title: "Was ist Somatic Experiencing — und wie hilft es bei Stress?",
    category: "Somatic Experiencing & Regulation des Nervensystems",
    date: "2026-05-12",
    readingTime: "6",
    excerpt:
      "Eine zugängliche Einführung in Somatic Experiencing, das Nervensystem und warum der Körper zählt, wenn wir unter Stress stehen.",
    body: [
      { type: "p", text: "Die meisten von uns sind es gewohnt, Stress als etwas zu betrachten, das im Kopf geschieht — eine Sache von Gedanken, Sorgen und To-do-Listen. Und das ist er auch. Aber Stress lebt auch im Körper. Ihr Herzschlag, Ihre Atmung, die Anspannung in den Schultern, der Knoten im Magen: Das sind keine Nebenwirkungen eines stressigen Lebens. Sie sind Teil dessen, wie Stress tatsächlich wirkt." },
      { type: "p", text: "Somatic Experiencing (SE) ist ein körperorientierter Ansatz, entwickelt von Dr. Peter Levine, der dies ernst nimmt. Er arbeitet mit dem Nervensystem und dem gespürten Sinn des Körpers, um Menschen dabei zu unterstützen, durch Stress und überwältigende Erfahrungen hindurchzugehen — nicht indem er sie aus der Distanz analysiert, sondern indem er dem Körper behutsam hilft, zu vollenden, was er damals nicht vollenden konnte." },
      { type: "h2", text: "Ein kurzer Rundgang durch das Nervensystem" },
      { type: "p", text: "Ihr autonomes Nervensystem scannt ständig und leise nach Sicherheit und Bedrohung — lange bevor bewusstes Denken ins Spiel kommt. Wenn es eine Anforderung wahrnimmt, die es als zu viel einschätzt, mobilisiert es: der vertraute Energieschub von Kampf oder Flucht. Wenn sich etwas überwältigend oder ausweglos anfühlt, kann es das Gegenteil tun — herunterfahren, taub werden, erstarren." },
      { type: "p", text: "Diese Reaktionen sind intelligent und schützend. Die Schwierigkeit besteht darin, dass das Nervensystem unter anhaltendem Druck in einem Zustand hoher Aktivierung oder des Herunterfahrens steckenbleiben kann, selbst nachdem die Anforderung vorüber ist. Sie bemerken das vielleicht als ein Gefühl, dauerhaft unter Strom zu stehen, angespannt, erschöpft oder seltsam flach zu sein — als hätte der Körper die Botschaft nie ganz erhalten, dass es sicher ist, sich zu beruhigen." },
      { type: "h2", text: "Was Somatic Experiencing tatsächlich umfasst" },
      { type: "p", text: "SE ist behutsam und allmählich. Statt Sie zu bitten, schwierige Ereignisse im Detail noch einmal zu durchleben, richtet es sorgfältige Aufmerksamkeit auf das gegenwärtige Erleben des Körpers — Empfindungen, kleine Impulse, feine Verschiebungen von Anspannung und Leichtigkeit." },
      { type: "ul", items: [
        "Ein Bewusstsein für Körperempfindungen aufbauen, Stück für Stück, innerhalb eines Bereichs, den Sie aushalten können.",
        "Bemerken, wo Anspannung oder Aktivierung ist — und, ebenso wichtig, wo Stabilität und Leichtigkeit sind.",
        "Dem Nervensystem erlauben, gehaltene Energie langsam zu entladen, sodass sich das Beruhigen sicher anfühlt statt überflutend.",
        "Ihren gespürten Sinn von Erdung stärken, sodass Regulation im Alltag verfügbarer wird.",
      ] },
      { type: "p", text: "Ein wichtiges Prinzip ist, dass mehr nicht besser ist. SE arbeitet innerhalb der Kapazität eines Menschen und bewegt sich hin und her zwischen Aktivierung und Ruhe, sodass das System erfahrungsbasiert lernt, dass es aus dem Stress heraus und zurück ins Gleichgewicht gelangen kann. Mit der Zeit neigt diese Flexibilität dazu, sich zu verallgemeinern — Sie erholen sich ein wenig schneller, beruhigen sich ein wenig leichter." },
      { type: "h2", text: "Warum der Körper zählt, wenn wir unter Stress stehen" },
      { type: "p", text: "Einsicht allein — zu verstehen, warum Sie sich fühlen, wie Sie sich fühlen — ist wertvoll, ändert aber nicht immer, wie der Körper reagiert. Sie können rational wissen, dass Sie sicher sind, und dennoch spüren, wie sich Ihre Brust zusammenzieht, sobald eine bestimmte E-Mail eintrifft. Genau in dieser Kluft kann körperorientierte Arbeit helfen. Indem SE das Nervensystem direkt einbezieht, unterstützt es Veränderung auf der Ebene, auf der Stress tatsächlich gehalten wird." },
      { type: "p", text: "In meiner eigenen Arbeit ist Somatic Experiencing eine Perspektive unter mehreren. Ich schöpfe daraus neben systemischen und achtsamkeitsbasierten Ansätzen, je nachdem, was sich für den Menschen vor mir hilfreich anfühlt. Für manche Menschen ist die Aufmerksamkeit für den Körper das fehlende Stück; für andere ist sie ein Strang einer umfassenderen Erkundung." },
      { type: "h2", text: "Eine sanftere Beziehung zu den eigenen Reaktionen" },
      { type: "p", text: "Das vielleicht still wirksamste, was SE bietet, ist eine Veränderung in der Beziehung zu den eigenen Reaktionen. Statt Ihre Anspannung zu bekämpfen oder sich von Ihrer Erschöpfung erschrecken zu lassen, beginnen Sie, diesen Zuständen mit Neugier zu begegnen — als bedeutsame Signale eines Systems, das sein Bestes getan hat, um Sie zu schützen. Von dort aus haben Erdung und Stabilität Raum zu wachsen." },
    ],
  },
  {
    slug: "why-big-life-changes-feel-harder",
    title: "Warum sich große Lebensveränderungen schwerer anfühlen, als sie „sollten\"",
    category: "Lebensübergänge",
    date: "2026-04-22",
    readingTime: "5",
    excerpt:
      "Warum Übergänge emotional fordernd sind, selbst wenn sie positiv sind — und was hilft, wenn Sie sich durch Veränderung hindurch unsicher fühlen.",
    body: [
      { type: "p", text: "Ein neuer Job. Ein Umzug in eine Stadt, die Sie gewählt haben. Eine Beziehung, die beginnt, oder ein lang gehegter Traum, der endlich Wirklichkeit wird. Nach jedem äußeren Maßstab läuft es gut — und doch fühlen Sie sich unerwartet unsicher, müde oder seltsam traurig. Wenn ein Teil von Ihnen leise fragt, warum das so schwer ist, obwohl nichts falsch läuft, sind Sie damit nicht allein." },
      { type: "p", text: "Wir neigen anzunehmen, dass schwierige Gefühle zu schwierigen Ereignissen gehören. Wenn uns also eine positive Veränderung desorientiert, fügen wir oft eine zweite Schicht der Belastung auf die erste: So sollte ich mich nicht fühlen. Aber Übergänge sind ihrer Natur nach fordernd — nicht weil etwas schiefgelaufen ist, sondern weil Veränderung uns viel abverlangt, selbst wenn sie willkommen ist." },
      { type: "h2", text: "Jeder Gewinn enthält einen Verlust" },
      { type: "p", text: "Unter fast jeder bedeutsamen Veränderung liegt etwas, das zurückgelassen wird. Eine neue Rolle bedeutet, die Geborgenheit der Kompetenz loszulassen, die Sie in der alten hatten. Ein Schritt nach vorn im Leben kann leise die Tür zu einer Version Ihrer selbst oder einer Lebensweise schließen, an der Sie hingen. Diese Verluste sind oft unsichtbar — auch für uns selbst —, was mit ein Grund dafür ist, dass die Gefühle, die mit ihnen kommen, so verwirrend sein können." },
      { type: "p", text: "Den Verlust im Gewinn zu benennen ist oft eine Erleichterung. Es erklärt die Trauer, die unerwartet neben echter Vorfreude sitzen kann. Sie sind nicht undankbar. Sie verarbeiten eine reale Veränderung." },
      { type: "h2", text: "Übergänge verlangen vom Nervensystem, sich neu einzustellen" },
      { type: "p", text: "Vertrautheit ist eine Form von Sicherheit. Selbst Routinen, über die wir uns beklagen, bieten eine Art Gerüst, auf das sich das Nervensystem verlässt. Wenn sich dieses Gerüst verändert — neue Umgebung, neue Menschen, neue Erwartungen —, muss der Körper härter arbeiten und sich an alles aufs Neue orientieren. Diese zusätzliche Anstrengung ist real, und sie ist ermüdend, weshalb Übergänge so oft mit einer Erschöpfung einhergehen, die reine Logik nicht erklären kann." },
      { type: "ul", items: [
        "Das „Dazwischen\"-Gefühl — nicht mehr, wer Sie waren, noch nicht, wer Sie werden.",
        "Erhöhte Empfindsamkeit, Selbstzweifel oder eine kürzere Zündschnur als sonst.",
        "Müdigkeit, die sich durch Ruhe nicht ganz auflöst.",
        "Wellen von Gefühlen, die im Verhältnis zu den Ereignissen unangemessen scheinen.",
      ] },
      { type: "h2", text: "Der Raum dazwischen ist kein Fehler" },
      { type: "p", text: "Viele Traditionen beschreiben Übergang als eine Schwelle — einen liminalen Raum zwischen einer alten Struktur und einer neuen. Er ist gerade deshalb unbequem, weil er ungeformt ist. Aber er ist auch der Ort, an dem echte Neuorientierung geschieht. Sich zu beeilen, um sich gefestigt zu fühlen, kann genau den Prozess kurzschließen, der es etwas Neuem erlaubt, Gestalt anzunehmen." },
      { type: "p", text: "Was meist hilft, ist Erlaubnis: sich unsicher fühlen zu dürfen, ohne es als Problem zu behandeln, das gelöst werden muss; sich in einem menschlichen Tempo zu bewegen; in Kontakt mit Ihren Werten zu bleiben, während sich die äußeren Einzelheiten neu ordnen." },
      { type: "h2", text: "Begleitung durch das Dazwischen" },
      { type: "p", text: "Beratung kann einen verlässlichen Bezugspunkt bieten, während sich alles andere verschiebt — einen reflexiven Raum, um zu verstehen, was zurückgelassen wird, was von Ihnen verlangt wird und was am meisten zählt, während Sie sich vorwärtsbewegen. Nicht um den Übergang zu beschleunigen, sondern um Ihnen zu helfen, mit mehr Stabilität und Selbstverständnis hindurchzugehen." },
      { type: "p", text: "Wenn eine Veränderung, die sich gut anfühlen sollte, Sie verletzlicher zurücklässt, als Sie erwartet haben, nehmen Sie es als Zeichen dafür, wie viel der Moment Ihnen abverlangt — und wie sehr er zählt. Das ist keine Schwäche. Es ist die ganz gewöhnliche, fordernde Arbeit des Werdens." },
    ],
  },
];
