import type { BlogPost } from "../types";

export const setCEn: BlogPost[] = [
  {
    slug: "counselling-vs-therapy-vs-coaching",
    title: "Counselling vs Therapy vs Coaching: What's the Difference?",
    category: "Understanding Counselling",
    date: "2026-07-01",
    readingTime: "7",
    excerpt:
      "A clear, jargon-free guide to how counselling, psychotherapy, and coaching differ — and how to choose what fits.",
    body: [
      { type: "p", text: "If you have ever tried to find support for a hard patch in your life, you will know how confusing the words can be. Counselling, psychotherapy, coaching — they sound similar, they overlap in places, and the people offering them do not always explain how they differ. This guide is here to make that clearer, in plain language, so you can choose what actually fits your situation." },
      { type: "p", text: "The short version: these are related but distinct kinds of support, offered by different professionals for different purposes. Knowing what each one is for can save you a lot of time, and help you feel confident that you are asking for the right thing." },
      { type: "h2", text: "What counselling is" },
      { type: "p", text: "Counselling is a structured, confidential space to reflect on what is going on in your life and how you are relating to it. It works well with the ordinary but demanding stuff of being human: stress, overwhelm, exhaustion, a sense of feeling stuck, disconnection from yourself or the people around you, and the unsteadiness that comes with big life changes. The focus is on the present and the near future — making sense of where you are, and finding gentler, more sustainable ways forward." },
      { type: "p", text: "As a Systemic and Integrative Counsellor, this is the support I offer. Systemic means I pay attention to the relationships and contexts you live within, not just what happens inside you. Integrative means I draw on more than one approach — including body-oriented work such as Somatic Experiencing — depending on what is useful for you. You can read more about how I think and work on my [about page](/about), and about the shape of the sessions themselves on the [work together page](/work-with-me)." },
      { type: "h2", text: "What psychotherapy is — and where it differs" },
      { type: "p", text: "Psychotherapy is a separate, regulated field. In many countries it is a protected, medical or clinical service, provided by licensed psychotherapists, clinical psychologists, or psychiatrists. It typically involves the assessment and treatment of diagnosed mental health conditions, often over a longer period and at greater depth, and it may sit alongside medical care." },
      { type: "p", text: "This is an important line, and I want to be clear about it: I do not provide psychotherapy, treatment, or diagnosis. Those belong to a different, regulated profession. Counselling and psychotherapy share some tools and a caring, attentive stance, but they are not the same service — and where a clinical condition needs assessment or treatment, that is work for a licensed psychotherapist or doctor, not a counsellor." },
      { type: "p", text: "None of this is a ranking. One is not \"deeper\" or \"better\" than the other; they simply do different jobs. Many people move between them over a lifetime, and a good counsellor will always tell you honestly when what you need sits outside the scope of counselling." },
      { type: "h2", text: "What coaching is" },
      { type: "p", text: "Coaching is another distinct service, usually provided by coaches, and it tends to be goal- and performance-oriented. Think career direction, leadership, productivity, a specific project or transition you want to move through. Coaching generally looks forward — clarifying goals and building strategies to reach them — and is less concerned with the emotional history behind where you are." },
      { type: "p", text: "There is genuine overlap with counselling, especially around life direction and change. The difference is one of emphasis. Coaching asks \"where do you want to get to, and how?\" Counselling makes more room for \"how are you, really, and what is this experience asking of you?\" — including the feelings, patterns, and pressures underneath the goals." },
      { type: "h2", text: "How to choose what fits" },
      { type: "p", text: "You do not need a perfect diagnosis of your own situation before you reach out. But a few gentle questions can point you in the right direction:" },
      { type: "ul", items: [
        "If you are living with a diagnosed mental health condition, or you feel you may need clinical assessment or treatment, psychotherapy or medical care is the right place to start.",
        "If you are carrying stress, overwhelm, exhaustion, or a sense of being stuck, and you want a reflective space to understand it and find your footing, counselling is likely a good fit.",
        "If you have a clear external goal and want structured support to reach it, coaching may serve you best.",
        "If you are simply not sure, it is completely fine to say so — a short conversation usually makes the picture much clearer.",
      ] },
      { type: "p", text: "This is exactly what a first, no-pressure conversation is for. If you would like help working out whether counselling fits what you are going through, you are welcome to [book a discovery call](/contact) or look through the [frequently asked questions](/faq) first. And if it turns out that what you need lies elsewhere, I will say so plainly and point you in a more helpful direction." },
      { type: "p", text: "The most important thing is not getting the label exactly right on the first try. It is taking the step of asking for support — and trusting that the right kind of help can be found." },
    ],
  },
  {
    slug: "how-online-counselling-works",
    title: "How Online Counselling Works — and How to Get the Most From It",
    category: "Online Counselling",
    date: "2026-06-24",
    readingTime: "7",
    excerpt:
      "What to expect from online counselling, whether it really works, and practical tips for a good session.",
    body: [
      { type: "p", text: "For a long time, counselling meant travelling to an office, sitting in a waiting room, and meeting in person. That still has its place. But for a growing number of people — especially those living international lives, working across time zones, or simply short on time — online counselling has become the way they get support. If you are wondering how it works and whether it is really as good, this guide is for you." },
      { type: "p", text: "The honest answer is that online counselling can be every bit as meaningful as meeting in a room together. What matters most in counselling is the quality of the relationship and the attention you receive — and both of those travel surprisingly well through a screen." },
      { type: "h2", text: "What actually happens in an online session" },
      { type: "p", text: "In practice, an online session looks a lot like an in-person one, just held over a secure video call. We agree a time, you find a quiet and private spot, and we meet face to face on screen for the session. We talk, we pause, we notice what comes up — the same reflective, unhurried process, simply in a different setting." },
      { type: "p", text: "Because my work is often body-aware, drawing on approaches like Somatic Experiencing, we can still pay attention to what is happening in your body as we talk — the tightness in your shoulders, the pace of your breath, the moment something eases. You can learn more about that side of the work in [what is Somatic Experiencing](/blog/what-is-somatic-experiencing). None of that depends on being in the same room." },
      { type: "h2", text: "Does online counselling really work?" },
      { type: "p", text: "This is the question people ask most, and it is a fair one. Many people are surprised by how natural it feels once they begin. Being in your own space can actually help you settle and speak more openly than you might in an unfamiliar office. There is no commute afterwards, no rush back to your day — just a little time to let the session land." },
      { type: "p", text: "Online counselling also removes some very real barriers. It makes support possible when you have moved abroad, when there is no counsellor nearby who speaks your language, when your schedule is unpredictable, or when leaving the house on a hard day feels like too much. For people building a life across borders, that accessibility can be the difference between getting support and going without. If that is your situation, you may find [finding an English-speaking counsellor when you live abroad](/blog/english-speaking-counsellor-abroad) helpful too." },
      { type: "h2", text: "Setting yourself up for a good session" },
      { type: "p", text: "A little preparation goes a long way. You do not need anything fancy — just a few simple conditions that let you be present:" },
      { type: "ul", items: [
        "A quiet, private space where you will not be overheard or interrupted for the length of the session.",
        "A stable internet connection, and headphones if you have them — they help the conversation feel more intimate.",
        "A comfortable seat, a glass of water, and perhaps a blanket or something grounding within reach.",
        "A few minutes beforehand to arrive properly — closing other tabs, silencing your phone, taking a breath.",
        "A small buffer afterwards, if you can, rather than jumping straight into your next meeting.",
      ] },
      { type: "p", text: "If privacy at home is difficult, we can think about that together — some people take their session in a parked car, in a booked room, or with headphones and a white-noise app running by the door. There is almost always a workable solution." },
      { type: "h2", text: "Getting the most from the work" },
      { type: "p", text: "The technology is only the container. What fills it is your willingness to be honest — with me and with yourself — and to let the session be whatever it needs to be that day. Some sessions are full of words; others are quieter and more reflective. Both are useful." },
      { type: "p", text: "It also helps to let things continue gently between sessions: noticing what stayed with you, giving yourself permission to feel it, sometimes jotting down a thought to bring back. Counselling is not only the hour we spend together; it is the slower shift that unfolds around it." },
      { type: "p", text: "If you are curious whether online counselling could work for you, the easiest next step is a short conversation. You can [book a discovery call](/contact) to talk it through, [get in touch](/contact) with any practical questions, or read the [frequently asked questions](/faq) if you would like more detail first. There is no pressure — just a chance to see how it feels." },
    ],
  },
  {
    slug: "english-speaking-counsellor-abroad",
    title: "Finding an English-Speaking Counsellor When You Live Abroad",
    category: "Expat Life",
    date: "2026-06-17",
    readingTime: "6",
    excerpt:
      "Why working in your own language matters, and how to find counselling support that fits an international life.",
    body: [
      { type: "p", text: "You have built a life in a new country. You order coffee in the local language, you navigate the paperwork, you have found your way around. And then something in your inner world needs attention — a stretch of stress, a loss, a growing sense of disconnection — and you realise you want to talk to someone who truly understands you. In English. That instinct is not a weakness. It is one of the most important things you can honour." },
      { type: "p", text: "Living abroad is rich and expanding, but it can also be quietly demanding. When you go looking for support in those moments, the language you speak matters far more than people expect." },
      { type: "h2", text: "Why your own language matters so much" },
      { type: "p", text: "Emotion lives in language, and usually in the language you grew up with. You can be perfectly fluent in a second language for work and daily life, and still find that your feelings do not translate. The precise word for a particular ache, the phrase your grandmother used, the way you naturally reach for humour or metaphor — these live in your mother tongue." },
      { type: "p", text: "In counselling, that precision is not a luxury. It is much of the work. When you have to translate your inner life before you can share it, part of your attention goes to the translating rather than the feeling. Working in English — or whichever language is truly yours — lets you drop that extra layer and simply say what is real, in the words that fit." },
      { type: "h2", text: "The particular weight of building a life abroad" },
      { type: "p", text: "There is also the content of what you may want to talk about. Much of it is bound up with being international: homesickness that surprises you, relationships stretched across distance, the strange grief of missing a home you also chose to leave, the effort of belonging in two places at once and sometimes feeling fully at home in neither." },
      { type: "p", text: "A counsellor who understands international life does not need all of this explained from scratch. That shared understanding lets you get to what matters more quickly. If any of this resonates, you may find [built a life abroad but it doesn't feel like home](/blog/built-a-life-abroad-not-at-home) speaks to it directly. Working in your own language, with someone who knows the terrain, can be a real relief." },
      { type: "h2", text: "Where the online part helps" },
      { type: "p", text: "The good news is that living abroad no longer limits you to whoever happens to be nearby. Online counselling means you can work with someone whose language and approach genuinely fit, wherever you both are. You are no longer choosing between the local counsellor who does not share your language and no support at all." },
      { type: "p", text: "It also brings a welcome continuity. If your international life involves further moves, an online counsellor can stay with you across them — one steady relationship while the geography around you keeps shifting. For many people that stability is exactly what they most need." },
      { type: "h2", text: "What to look for" },
      { type: "p", text: "As you search, a few things are worth weighing up beyond language alone:" },
      { type: "ul", items: [
        "Someone who understands the international, cross-cultural experience from the inside, not just in theory.",
        "An approach that fits what you are carrying — for stress, overwhelm, and life transitions, a warm and practical counselling style tends to serve well.",
        "Comfortable, secure online working, so distance and time zones are not an obstacle.",
        "A relationship that feels right to you — which usually only becomes clear in a first conversation.",
      ] },
      { type: "p", text: "I offer counselling online, internationally, in both English and German, and I know the terrain of international life from my own experience. You can read more about my background on my [about page](/about) or explore how sessions work on the [work together page](/work-with-me)." },
      { type: "p", text: "If you have been quietly wishing for someone who simply gets it — in your own words — that wish is worth acting on. You are welcome to [get in touch](/contact) whenever you feel ready. Reaching out in your own language, to someone who understands, can be the moment things start to feel a little lighter." },
    ],
  },
  {
    slug: "relocation-stress-adjusting-new-country",
    title: "The Hidden Weight of Relocation: Adjusting to a New Country",
    category: "Life Transitions",
    date: "2026-06-10",
    readingTime: "7",
    excerpt:
      "Why relocating is quietly exhausting, the stages of adjustment, and gentle ways to support yourself.",
    body: [
      { type: "p", text: "Moving to a new country is often framed as an adventure, and it is. But somewhere between the excitement of arriving and the story you tell friends back home, there is a quieter truth: relocation is tiring in ways that are hard to explain, even to yourself. If you have moved and found yourself unexpectedly flat, on edge, or exhausted, nothing has gone wrong. You are carrying a hidden weight that almost every mover carries." },
      { type: "p", text: "Understanding that weight — where it comes from, and how it tends to move through us — can make the whole experience feel less bewildering, and a good deal more manageable." },
      { type: "h2", text: "Why relocation is so quietly exhausting" },
      { type: "p", text: "On the surface, a move is a set of tasks: the visa, the flights, the new home, the paperwork. Underneath, something much larger is happening. Almost every automatic part of your life has stopped being automatic. Where to buy bread, how the transport works, what a gesture means, how to phrase a polite request — a hundred small decisions a day that used to run in the background now need your conscious attention." },
      { type: "p", text: "That constant low-level effort is genuinely depleting, even when nothing dramatic is going wrong. Add the loss of your familiar network — the friends, routines, and places that quietly held you — and it is no wonder relocation leaves people feeling stretched thin. This is not fragility. It is the predictable cost of rebuilding an entire life at once." },
      { type: "h2", text: "The stages of adjustment" },
      { type: "p", text: "Adjustment tends to move in loose phases. They do not arrive on a schedule, and you may loop back through them more than once, but recognising them can be steadying." },
      { type: "ul", items: [
        "An early lift, where the newness feels exciting and everything is interesting — the honeymoon of arrival.",
        "A dip, where the differences start to grate, small frustrations pile up, and homesickness or irritability surfaces.",
        "A gradual settling, where you build routines, find your bearings, and the new place slowly becomes less foreign.",
        "A deeper adaptation, where the new country starts to feel, at least in part, like somewhere you belong.",
      ] },
      { type: "p", text: "The dip is the part that catches people off guard, because it often comes after the excitement, when they expected to feel settled. Knowing it is a normal stage rather than a sign of failure can take a lot of the sting out of it." },
      { type: "h2", text: "The grief nobody warns you about" },
      { type: "p", text: "There is often a quiet grief woven through relocation, even a chosen and happy one. You are not only gaining a new life; you are also leaving one behind — a version of yourself, a set of relationships, a place that knew you. It is possible to feel genuinely glad you moved and genuinely sad about what you left, at the same time. Both are true, and holding both is part of adjusting." },
      { type: "p", text: "If that mixed feeling lingers — the sense of having built something new that does not yet feel like home — you may find [built a life abroad but it doesn't feel like home](/blog/built-a-life-abroad-not-at-home) speaks to it more fully. It is a very common experience, and not a permanent one." },
      { type: "h2", text: "Gentle ways to support yourself" },
      { type: "p", text: "You cannot rush adjustment, but you can be kinder to yourself while it happens. A few things tend to help:" },
      { type: "ul", items: [
        "Lower your expectations of yourself for a while — you are doing something genuinely demanding, and it is fair to have less capacity than usual.",
        "Keep small threads of the familiar: a food, a ritual, a regular call home, a language that feels like yours.",
        "Build new routines slowly, one anchor at a time, rather than expecting a whole life to click into place at once.",
        "Let yourself feel the harder emotions rather than pushing them down — they tend to pass through more easily when acknowledged.",
        "Reach out before you are at the end of your reserves, not only once you are.",
      ] },
      { type: "p", text: "And you do not have to carry it alone. Counselling can offer a steady space to make sense of the transition, feel what needs feeling, and find your footing at your own pace — especially valuable when the people around you are new and your usual support is far away. If any of this feels familiar, you are welcome to [book a discovery call](/contact) or [get in touch](/contact) whenever you are ready. The weight of relocation is real, and so is the possibility of setting it down a little." },
    ],
  },
];

export const setCDe: BlogPost[] = [
  {
    slug: "counselling-vs-therapy-vs-coaching",
    title: "Beratung, Psychotherapie und Coaching: Wo liegt der Unterschied?",
    category: "Beratung verstehen",
    date: "2026-07-01",
    readingTime: "7",
    excerpt:
      "Ein klarer, verständlicher Überblick, wie sich Beratung, Psychotherapie und Coaching unterscheiden — und wie Sie das Passende für sich finden.",
    body: [
      { type: "p", text: "Wenn Sie schon einmal Unterstützung für eine schwierige Phase in Ihrem Leben gesucht haben, kennen Sie vielleicht die Verwirrung um die Begriffe. Beratung, Psychotherapie, Coaching — sie klingen ähnlich, überschneiden sich stellenweise, und wer sie anbietet, erklärt den Unterschied nicht immer. Dieser Überblick soll für Klarheit sorgen, in verständlicher Sprache, damit Sie wählen können, was wirklich zu Ihrer Situation passt." },
      { type: "p", text: "Kurz gesagt: Es sind verwandte, aber unterschiedliche Formen der Unterstützung, angeboten von verschiedenen Fachpersonen und mit verschiedenen Zielen. Wenn Sie wissen, wofür jede gedacht ist, sparen Sie viel Zeit — und können sicher sein, dass Sie nach dem Richtigen fragen." },
      { type: "h2", text: "Was Beratung ist" },
      { type: "p", text: "Beratung ist ein strukturierter, vertraulicher Raum, um über das nachzudenken, was in Ihrem Leben geschieht, und darüber, wie Sie sich dazu verhalten. Sie eignet sich gut für das Alltägliche und doch Fordernde des Menschseins: Stress, Überforderung, Erschöpfung, das Gefühl festzustecken, die Entfremdung von sich selbst oder den Menschen um Sie herum und die Verunsicherung, die große Lebensveränderungen mit sich bringen. Der Fokus liegt auf der Gegenwart und der nahen Zukunft — zu verstehen, wo Sie stehen, und sanftere, tragfähigere Wege nach vorn zu finden." },
      { type: "p", text: "Als systemische und integrative Beraterin ist dies die Unterstützung, die ich anbiete. Systemisch heißt, dass ich die Beziehungen und Zusammenhänge in den Blick nehme, in denen Sie leben, nicht nur das, was in Ihnen vorgeht. Integrativ heißt, dass ich auf mehr als einen Ansatz zurückgreife — darunter körperorientierte Arbeit wie Somatic Experiencing —, je nachdem, was Ihnen guttut. Mehr darüber, wie ich denke und arbeite, lesen Sie auf meiner [Über-mich-Seite](/de/ueber-mich) und über den Ablauf der Sitzungen auf der [Seite zur Zusammenarbeit](/de/angebot)." },
      { type: "h2", text: "Was Psychotherapie ist — und wo sie sich unterscheidet" },
      { type: "p", text: "Psychotherapie ist ein eigenständiges, reguliertes Fachgebiet. In vielen Ländern ist sie eine geschützte, medizinische oder klinische Leistung, die von approbierten Psychotherapeut:innen, klinischen Psycholog:innen oder Psychiater:innen erbracht wird. Sie umfasst in der Regel die Abklärung und Behandlung diagnostizierter psychischer Erkrankungen, oft über einen längeren Zeitraum und in größerer Tiefe, und sie kann Teil einer medizinischen Versorgung sein." },
      { type: "p", text: "Das ist eine wichtige Grenze, und ich möchte sie klar benennen: Ich biete keine Psychotherapie, keine Behandlung und keine Diagnose an. Das gehört zu einem anderen, regulierten Berufsfeld. Beratung und Psychotherapie teilen manche Werkzeuge und eine zugewandte, aufmerksame Haltung, aber sie sind nicht dieselbe Leistung — und wo ein klinisches Anliegen abgeklärt oder behandelt werden muss, ist das Sache approbierter Psychotherapeut:innen oder Ärzt:innen, nicht einer Beraterin." },
      { type: "p", text: "Nichts davon ist eine Rangordnung. Das eine ist nicht \"tiefer\" oder \"besser\" als das andere; sie erfüllen einfach unterschiedliche Aufgaben. Viele Menschen wechseln im Lauf ihres Lebens zwischen ihnen, und eine gute Beraterin sagt Ihnen immer ehrlich, wenn das, was Sie brauchen, über den Rahmen der Beratung hinausgeht." },
      { type: "h2", text: "Was Coaching ist" },
      { type: "p", text: "Coaching ist eine weitere eigenständige Leistung, die meist von Coaches angeboten wird und in der Regel ziel- und leistungsorientiert ausgerichtet ist. Denken Sie an berufliche Orientierung, Führung, Produktivität, ein bestimmtes Projekt oder einen Übergang, den Sie meistern möchten. Coaching blickt in der Regel nach vorn — Ziele klären und Strategien entwickeln, um sie zu erreichen — und kümmert sich weniger um die emotionale Vorgeschichte hinter Ihrer aktuellen Lage." },
      { type: "p", text: "Mit der Beratung gibt es echte Überschneidungen, besonders bei Lebensrichtung und Veränderung. Der Unterschied liegt in der Gewichtung. Coaching fragt: \"Wohin möchten Sie, und wie kommen Sie dorthin?\" Beratung schafft mehr Raum für: \"Wie geht es Ihnen wirklich, und was fordert diese Erfahrung von Ihnen?\" — samt der Gefühle, Muster und Belastungen unter den Zielen." },
      { type: "h2", text: "Wie Sie das Passende für sich finden" },
      { type: "p", text: "Sie müssen Ihre eigene Situation nicht perfekt einordnen, bevor Sie sich melden. Doch ein paar behutsame Fragen können Ihnen die Richtung weisen:" },
      { type: "ul", items: [
        "Wenn Sie mit einer diagnostizierten psychischen Erkrankung leben oder das Gefühl haben, dass eine klinische Abklärung oder Behandlung nötig sein könnte, sind Psychotherapie oder medizinische Versorgung der richtige Ausgangspunkt.",
        "Wenn Sie Stress, Überforderung, Erschöpfung oder das Gefühl festzustecken mit sich tragen und einen reflektierenden Raum suchen, um das zu verstehen und wieder Halt zu finden, ist Beratung wahrscheinlich gut geeignet.",
        "Wenn Sie ein klares äußeres Ziel haben und strukturierte Unterstützung wünschen, um es zu erreichen, ist Coaching womöglich am besten für Sie.",
        "Und wenn Sie schlicht unsicher sind, ist es völlig in Ordnung, das so zu sagen — ein kurzes Gespräch macht das Bild meist deutlich klarer.",
      ] },
      { type: "p", text: "Genau dafür ist ein erstes, unverbindliches Gespräch da. Wenn Sie herausfinden möchten, ob Beratung zu dem passt, was Sie gerade durchleben, können Sie gern ein [Kennenlerngespräch buchen](/de/contact) oder vorab die [häufigen Fragen](/de/faq) durchsehen. Und falls sich zeigt, dass das, was Sie brauchen, woanders liegt, sage ich Ihnen das offen und weise Ihnen eine hilfreichere Richtung." },
      { type: "p", text: "Das Wichtigste ist nicht, gleich beim ersten Versuch das richtige Etikett zu treffen. Es ist der Schritt, um Unterstützung zu bitten — und darauf zu vertrauen, dass sich die passende Hilfe finden lässt." },
    ],
  },
  {
    slug: "how-online-counselling-works",
    title: "Wie Online-Beratung funktioniert — und wie Sie das Beste daraus machen",
    category: "Online-Beratung",
    date: "2026-06-24",
    readingTime: "7",
    excerpt:
      "Was Sie von Online-Beratung erwarten können, ob sie wirklich wirkt und praktische Tipps für eine gute Sitzung.",
    body: [
      { type: "p", text: "Lange Zeit hieß Beratung, in eine Praxis zu fahren, im Wartezimmer zu sitzen und sich persönlich zu treffen. Das hat nach wie vor seinen Platz. Doch für immer mehr Menschen — besonders für jene, die international leben, über Zeitzonen hinweg arbeiten oder schlicht wenig Zeit haben — ist Online-Beratung zu dem Weg geworden, auf dem sie Unterstützung finden. Wenn Sie sich fragen, wie das funktioniert und ob es wirklich genauso gut ist, ist dieser Überblick für Sie." },
      { type: "p", text: "Die ehrliche Antwort lautet: Online-Beratung kann genauso bedeutsam sein wie ein Treffen in einem gemeinsamen Raum. Worauf es in der Beratung am meisten ankommt, ist die Qualität der Beziehung und die Aufmerksamkeit, die Sie erfahren — und beides überträgt sich erstaunlich gut über einen Bildschirm." },
      { type: "h2", text: "Was in einer Online-Sitzung tatsächlich passiert" },
      { type: "p", text: "In der Praxis sieht eine Online-Sitzung einer vor Ort sehr ähnlich, nur findet sie über einen sicheren Videoanruf statt. Wir vereinbaren einen Termin, Sie suchen sich einen ruhigen, geschützten Ort, und wir begegnen uns für die Sitzung von Angesicht zu Angesicht auf dem Bildschirm. Wir sprechen, wir halten inne, wir nehmen wahr, was auftaucht — derselbe reflektierende Prozess, ganz ohne Eile, nur eben in einem anderen Rahmen." },
      { type: "p", text: "Da meine Arbeit oft körperbewusst ist und auf Ansätze wie Somatic Experiencing zurückgreift, können wir auch weiterhin darauf achten, was in Ihrem Körper vorgeht, während wir sprechen — die Enge in den Schultern, das Tempo Ihres Atems, der Moment, in dem sich etwas löst. Mehr über diese Seite der Arbeit erfahren Sie in [Was ist Somatic Experiencing](/de/blog/what-is-somatic-experiencing). Nichts davon setzt voraus, im selben Raum zu sein." },
      { type: "h2", text: "Wirkt Online-Beratung wirklich?" },
      { type: "p", text: "Das ist die Frage, die am häufigsten gestellt wird, und sie ist berechtigt. Viele sind überrascht, wie natürlich es sich anfühlt, sobald sie erst einmal begonnen haben. In der eigenen Umgebung zu sein kann Ihnen sogar helfen, anzukommen und offener zu sprechen, als Sie es in einer fremden Praxis vielleicht täten. Danach gibt es keinen Heimweg, keine Eile zurück in den Alltag — nur ein wenig Zeit, die Sitzung nachklingen zu lassen." },
      { type: "p", text: "Online-Beratung räumt auch einige ganz reale Hürden aus dem Weg. Sie macht Unterstützung möglich, wenn Sie ins Ausland gezogen sind, wenn es in der Nähe keine Beraterin gibt, die Ihre Sprache spricht, wenn Ihr Terminkalender unberechenbar ist oder wenn es an einem schweren Tag zu viel ist, das Haus zu verlassen. Für Menschen, die sich ein Leben über Grenzen hinweg aufbauen, kann diese Zugänglichkeit den Unterschied machen zwischen Unterstützung bekommen und ganz ohne bleiben. Falls das Ihre Situation ist, finden Sie vielleicht auch [Eine englischsprachige Beraterin finden, wenn Sie im Ausland leben](/de/blog/english-speaking-counsellor-abroad) hilfreich." },
      { type: "h2", text: "So schaffen Sie gute Bedingungen für die Sitzung" },
      { type: "p", text: "Ein wenig Vorbereitung bewirkt viel. Sie brauchen nichts Aufwendiges — nur ein paar einfache Voraussetzungen, die es Ihnen erlauben, ganz präsent zu sein:" },
      { type: "ul", items: [
        "Einen ruhigen, geschützten Ort, an dem Sie für die Dauer der Sitzung nicht mitgehört oder unterbrochen werden.",
        "Eine stabile Internetverbindung und, falls vorhanden, Kopfhörer — sie lassen das Gespräch vertrauter wirken.",
        "Einen bequemen Sitzplatz, ein Glas Wasser und vielleicht eine Decke oder etwas Erdendes in Reichweite.",
        "Ein paar Minuten vorher, um wirklich anzukommen — andere Tabs schließen, das Handy stummschalten, durchatmen.",
        "Nach Möglichkeit einen kleinen Puffer danach, statt gleich in den nächsten Termin zu hetzen.",
      ] },
      { type: "p", text: "Wenn Privatsphäre zu Hause schwierig ist, überlegen wir gemeinsam — manche halten ihre Sitzung im geparkten Auto, in einem gebuchten Raum oder mit Kopfhörern und einer White-Noise-App an der Tür. Fast immer findet sich eine praktikable Lösung." },
      { type: "h2", text: "So holen Sie das Beste aus der Arbeit heraus" },
      { type: "p", text: "Die Technik ist nur das Gefäß. Was es füllt, ist Ihre Bereitschaft, ehrlich zu sein — mit mir und mit sich selbst — und die Sitzung das sein zu lassen, was sie an diesem Tag sein muss. Manche Sitzungen sind voller Worte; andere sind stiller und nachdenklicher. Beides ist wertvoll." },
      { type: "p", text: "Es hilft auch, das Ganze zwischen den Sitzungen sanft weiterwirken zu lassen: wahrzunehmen, was bei Ihnen nachklingt, sich zu erlauben, es zu fühlen, manchmal einen Gedanken zu notieren, um ihn beim nächsten Mal mitzubringen. Beratung ist nicht nur die Stunde, die wir miteinander verbringen; sie ist die langsamere Entwicklung, die sich darum herum entfaltet." },
      { type: "p", text: "Wenn Sie neugierig sind, ob Online-Beratung für Sie infrage kommt, ist der einfachste nächste Schritt ein kurzes Gespräch. Sie können ein [Kennenlerngespräch buchen](/de/contact), um es zu besprechen, mit praktischen Fragen [Kontakt aufnehmen](/de/contact) oder vorab die [häufigen Fragen](/de/faq) lesen, wenn Sie erst mehr erfahren möchten. Es gibt keinen Druck — nur die Gelegenheit, zu spüren, wie es sich anfühlt." },
    ],
  },
  {
    slug: "english-speaking-counsellor-abroad",
    title: "Eine englischsprachige Beraterin finden, wenn Sie im Ausland leben",
    category: "Expat-Leben",
    date: "2026-06-17",
    readingTime: "6",
    excerpt:
      "Warum es wichtig ist, in der eigenen Sprache zu arbeiten, und wie Sie Beratung finden, die zu einem internationalen Leben passt.",
    body: [
      { type: "p", text: "Sie haben sich in einem neuen Land ein Leben aufgebaut. Sie bestellen Kaffee in der Landessprache, Sie kommen mit dem Papierkram zurecht, Sie haben sich eingelebt. Und dann braucht etwas in Ihrem Inneren Aufmerksamkeit — eine Phase voller Stress, ein Verlust, ein wachsendes Gefühl der Entfremdung — und Sie merken, dass Sie mit jemandem sprechen möchten, der Sie wirklich versteht. Auf Englisch. Dieser Impuls ist keine Schwäche. Er gehört zu den wichtigsten Dingen, die Sie ernst nehmen können." },
      { type: "p", text: "Im Ausland zu leben ist bereichernd und weitet den Horizont, kann aber zugleich still fordernd sein. Wenn Sie in solchen Momenten Unterstützung suchen, zählt die Sprache, in der Sie sprechen, weit mehr, als man denkt." },
      { type: "h2", text: "Warum die eigene Sprache so viel ausmacht" },
      { type: "p", text: "Gefühle leben in der Sprache, und meist in der, mit der Sie aufgewachsen sind. Sie können in einer Zweitsprache für Beruf und Alltag vollkommen fließend sein und trotzdem merken, dass sich Ihre Gefühle nicht übersetzen lassen. Das genaue Wort für einen bestimmten Schmerz, die Redewendung Ihrer Großmutter, die Art, wie Sie ganz selbstverständlich zu Humor oder Bildern greifen — das lebt in Ihrer Muttersprache." },
      { type: "p", text: "In der Beratung ist diese Genauigkeit kein Luxus. Sie ist ein großer Teil der Arbeit. Wenn Sie Ihr Innenleben erst übersetzen müssen, bevor Sie es mitteilen können, geht ein Teil Ihrer Aufmerksamkeit ins Übersetzen statt ins Fühlen. In Ihrer Sprache zu arbeiten — sei es Englisch oder welche Sprache auch immer wirklich Ihre ist — erlaubt Ihnen, diese zusätzliche Schicht fallen zu lassen und einfach das zu sagen, was wahr ist, in den Worten, die passen." },
      { type: "h2", text: "Das besondere Gewicht, sich im Ausland ein Leben aufzubauen" },
      { type: "p", text: "Da ist auch das, worüber Sie vielleicht sprechen möchten. Vieles davon hängt mit dem internationalen Leben zusammen: Heimweh, das Sie überrascht, Beziehungen, die sich über weite Entfernungen spannen, die eigentümliche Trauer, ein Zuhause zu vermissen, das Sie selbst verlassen haben, die Mühe, an zwei Orten zugleich dazuzugehören und sich manchmal an keinem von beiden ganz zu Hause zu fühlen." },
      { type: "p", text: "Einer Beraterin, die das internationale Leben kennt, müssen Sie das nicht von Grund auf erklären. Dieses gemeinsame Verständnis lässt Sie schneller zu dem kommen, worauf es ankommt. Falls Ihnen das bekannt vorkommt, spricht [Ein Leben im Ausland aufgebaut, das sich nicht wie Zuhause anfühlt](/de/blog/built-a-life-abroad-not-at-home) es vielleicht unmittelbar an. In der eigenen Sprache zu arbeiten, mit jemandem, der das Terrain kennt, kann eine echte Erleichterung sein." },
      { type: "h2", text: "Wo das Online-Format hilft" },
      { type: "p", text: "Die gute Nachricht: Im Ausland zu leben beschränkt Sie nicht länger auf die Menschen, die zufällig in der Nähe sind. Online-Beratung heißt, dass Sie mit jemandem arbeiten können, dessen Sprache und Ansatz wirklich passen, egal, wo Sie beide sich befinden. Sie müssen nicht mehr zwischen der Beraterin vor Ort, die Ihre Sprache nicht spricht, und gar keiner Unterstützung wählen." },
      { type: "p", text: "Sie bringt auch eine willkommene Kontinuität. Wenn Ihr internationales Leben weitere Umzüge mit sich bringt, kann eine Online-Beraterin Sie über sie hinweg begleiten — eine beständige Beziehung, während sich die Landkarte um Sie herum immer weiter verschiebt. Für viele Menschen ist genau diese Stabilität das, was sie am meisten brauchen." },
      { type: "h2", text: "Worauf Sie achten können" },
      { type: "p", text: "Bei Ihrer Suche lohnt es sich, über die Sprache hinaus ein paar Dinge abzuwägen:" },
      { type: "ul", items: [
        "Jemand, der die internationale, interkulturelle Erfahrung von innen kennt, nicht nur aus der Theorie.",
        "Ein Ansatz, der zu dem passt, was Sie mit sich tragen — bei Stress, Überforderung und Lebensübergängen tut ein warmer, praxisnaher Beratungsstil meist gut.",
        "Angenehmes, sicheres Arbeiten online, damit Entfernung und Zeitzonen kein Hindernis sind.",
        "Eine Beziehung, die sich für Sie stimmig anfühlt — was sich meist erst in einem ersten Gespräch zeigt.",
      ] },
      { type: "p", text: "Ich biete Beratung online und international an, auf Englisch und auf Deutsch, und ich kenne das Terrain des internationalen Lebens aus eigener Erfahrung. Mehr über meinen Hintergrund lesen Sie auf meiner [Über-mich-Seite](/de/ueber-mich), und wie die Sitzungen ablaufen, erfahren Sie auf der [Seite zur Zusammenarbeit](/de/angebot)." },
      { type: "p", text: "Wenn Sie sich insgeheim jemanden gewünscht haben, der es einfach versteht — in Ihren eigenen Worten —, dann ist dieser Wunsch es wert, ihm zu folgen. Sie sind willkommen, [Kontakt aufzunehmen](/de/contact), wann immer Sie sich bereit fühlen. In der eigenen Sprache jemanden anzusprechen, der versteht, kann der Moment sein, in dem sich die Dinge ein wenig leichter anfühlen." },
    ],
  },
  {
    slug: "relocation-stress-adjusting-new-country",
    title: "Das verborgene Gewicht eines Umzugs: sich in einem neuen Land einleben",
    category: "Lebensübergänge",
    date: "2026-06-10",
    readingTime: "7",
    excerpt:
      "Warum ein Umzug still erschöpfend ist, welche Phasen die Eingewöhnung durchläuft und sanfte Wege, sich selbst zu unterstützen.",
    body: [
      { type: "p", text: "Ein Umzug in ein neues Land wird gern als Abenteuer beschrieben, und das ist er auch. Doch irgendwo zwischen der Aufregung des Ankommens und der Geschichte, die Sie Freunden in der Heimat erzählen, liegt eine leisere Wahrheit: Ein Umzug ermüdet auf eine Weise, die sich schwer erklären lässt, selbst sich selbst gegenüber. Wenn Sie umgezogen sind und sich unerwartet niedergeschlagen, angespannt oder erschöpft gefühlt haben, ist nichts falsch gelaufen. Sie tragen ein verborgenes Gewicht, das fast jeder mit sich trägt, der umzieht." },
      { type: "p", text: "Dieses Gewicht zu verstehen — woher es kommt und wie es sich in uns bewegt — kann die ganze Erfahrung weniger verwirrend und deutlich leichter zu bewältigen machen." },
      { type: "h2", text: "Warum ein Umzug so still erschöpfend ist" },
      { type: "p", text: "An der Oberfläche ist ein Umzug eine Reihe von Aufgaben: das Visum, die Flüge, das neue Zuhause, der Papierkram. Darunter geschieht etwas viel Größeres. Fast alles, was in Ihrem Leben wie von selbst lief, läuft nicht mehr von selbst. Wo man Brot kauft, wie der Nahverkehr funktioniert, was eine Geste bedeutet, wie man eine höfliche Bitte formuliert — hundert kleine Entscheidungen am Tag, die früher nebenbei liefen, verlangen nun Ihre bewusste Aufmerksamkeit." },
      { type: "p", text: "Diese ständige, unterschwellige Anstrengung zehrt wirklich an den Kräften, selbst wenn nichts Dramatisches schiefgeht. Kommt noch der Verlust Ihres vertrauten Umfelds hinzu — der Freundschaften, Routinen und Orte, die Ihnen still Halt gegeben haben —, ist es kein Wunder, dass ein Umzug Menschen ausgelaugt zurücklässt. Das ist keine Zerbrechlichkeit. Es ist der absehbare Preis dafür, ein ganzes Leben auf einmal neu aufzubauen." },
      { type: "h2", text: "Die Phasen der Eingewöhnung" },
      { type: "p", text: "Die Eingewöhnung verläuft meist in losen Phasen. Sie halten sich an keinen Zeitplan, und Sie durchlaufen sie womöglich mehr als einmal, aber sie zu erkennen kann beruhigend sein." },
      { type: "ul", items: [
        "Ein anfänglicher Aufschwung, in dem sich das Neue aufregend anfühlt und alles interessant ist — die Flitterwochen des Ankommens.",
        "Ein Tief, in dem die Unterschiede zu reiben beginnen, sich kleine Frustrationen häufen und Heimweh oder Gereiztheit auftauchen.",
        "Ein allmähliches Sich-Einrichten, in dem Sie Routinen aufbauen, sich zurechtfinden und der neue Ort nach und nach weniger fremd wird.",
        "Eine tiefere Anpassung, in der das neue Land beginnt, sich zumindest teilweise wie ein Ort anzufühlen, an den Sie gehören.",
      ] },
      { type: "p", text: "Das Tief ist der Teil, der Menschen überrascht, denn es kommt oft nach der Aufregung, gerade wenn sie erwartet hatten, endlich angekommen zu sein. Zu wissen, dass es eine ganz normale Phase ist und kein Zeichen des Scheiterns, kann ihm viel von seiner Schärfe nehmen." },
      { type: "h2", text: "Die Trauer, vor der Sie niemand warnt" },
      { type: "p", text: "Durch einen Umzug zieht sich oft eine stille Trauer, selbst durch einen, den Sie gewählt haben und der Sie glücklich macht. Sie gewinnen nicht nur ein neues Leben; Sie lassen auch eines zurück — eine Version Ihrer selbst, ein Geflecht von Beziehungen, einen Ort, der Sie kannte. Man kann aufrichtig froh über den Umzug und zugleich aufrichtig traurig über das Zurückgelassene sein. Beides ist wahr, und beides auszuhalten gehört zum Einleben dazu." },
      { type: "p", text: "Wenn dieses zwiespältige Gefühl anhält — der Eindruck, sich etwas Neues aufgebaut zu haben, das sich noch nicht wie Zuhause anfühlt —, spricht [Ein Leben im Ausland aufgebaut, das sich nicht wie Zuhause anfühlt](/de/blog/built-a-life-abroad-not-at-home) es vielleicht umfassender an. Es ist eine sehr verbreitete Erfahrung, und keine bleibende." },
      { type: "h2", text: "Sanfte Wege, sich selbst zu unterstützen" },
      { type: "p", text: "Beschleunigen lässt sich die Eingewöhnung nicht, aber Sie können freundlicher mit sich umgehen, während sie geschieht. Ein paar Dinge helfen meist:" },
      { type: "ul", items: [
        "Schrauben Sie Ihre Erwartungen an sich selbst eine Weile herunter — Sie leisten gerade etwas wirklich Forderndes, und es ist völlig in Ordnung, weniger Kraft zu haben als sonst.",
        "Bewahren Sie sich kleine Fäden des Vertrauten: ein Gericht, ein Ritual, ein regelmäßiges Telefonat nach Hause, eine Sprache, die sich wie Ihre anfühlt.",
        "Bauen Sie neue Routinen langsam auf, einen Anker nach dem anderen, statt zu erwarten, dass ein ganzes Leben auf einen Schlag an seinen Platz fällt.",
        "Erlauben Sie sich, die schwereren Gefühle zu fühlen, statt sie hinunterzuschlucken — anerkannt ziehen sie meist leichter vorüber.",
        "Melden Sie sich, bevor Sie am Ende Ihrer Kräfte sind, und nicht erst, wenn es so weit ist.",
      ] },
      { type: "p", text: "Und Sie müssen es nicht allein tragen. Beratung kann einen beständigen Raum bieten, um den Übergang zu verstehen, zu fühlen, was gefühlt werden will, und in Ihrem eigenen Tempo wieder Halt zu finden — besonders wertvoll, wenn die Menschen um Sie herum neu sind und Ihre gewohnte Unterstützung weit weg ist. Falls Ihnen etwas davon vertraut vorkommt, sind Sie willkommen, ein [Kennenlerngespräch zu buchen](/de/contact) oder [Kontakt aufzunehmen](/de/contact), wann immer Sie bereit sind. Das Gewicht eines Umzugs ist real — und ebenso die Möglichkeit, es ein wenig abzulegen." },
    ],
  },
];
